package mis.autoves.pages;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

/**
 * @author salturk
 */
public class ParametersPage extends javax.swing.JFrame
{

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> SubTypeComboBox;
    private javax.swing.JCheckBox airtv2Checkbox;
    private javax.swing.JCheckBox airtv2FlashdriveCheckbox;
    private javax.swing.JCheckBox airtvAntennaCheckbox;
    private javax.swing.JCheckBox airtvAnywhereCheckbox;
    private javax.swing.JLabel airtvLabel;
    private javax.swing.JLabel boxesLabel;
    private javax.swing.JLabel channelLabel;
    private javax.swing.JCheckBox cinemaxCheckbox;
    private javax.swing.JButton dvrAddButton;
    private javax.swing.JButton dvrEditButton;
    private javax.swing.JLabel dvrLabel;
    private javax.swing.JSeparator dvtStbSerparator;
    private javax.swing.JLabel extrasLabel;
    private javax.swing.JCheckBox hboCheckbox;
    private javax.swing.JCheckBox hdeliteCheckbox;
    private javax.swing.JLabel internetPackagesLabel;
    private javax.swing.JSeparator internetPhoneSeparator;
    private javax.swing.JSeparator internetSeparator1;
    private javax.swing.JLabel internetServicesLabel;
    private javax.swing.JComboBox<String> internetSpeedCombobox;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton newPhoneButton;
    private javax.swing.JLabel phoneFiberLabel;
    private javax.swing.JLabel phoneServicesLabel;
    private javax.swing.JCheckBox purchasedRouterCheckbox;
    private javax.swing.JButton resetAllButton;
    private javax.swing.JCheckBox routerCheckbox;
    private javax.swing.JCheckBox showtimeCheckbox;
    private javax.swing.JCheckBox sportstierCheckbox;
    private javax.swing.JCheckBox starzCheckbox;
    private javax.swing.JComboBox<String> stbCombobox;
    private javax.swing.JButton stbEditButton;
    private javax.swing.JLabel stbLabel;
    private javax.swing.JLabel subTypeLabel;
    private javax.swing.JButton submitAllButton;
    private javax.swing.JSeparator tvInternetSeparator;
    private javax.swing.JComboBox<String> tvPackagesCombobox;
    private javax.swing.JLabel tvPackagesLabel;
    private javax.swing.JSeparator tvSeparator1;
    private javax.swing.JSeparator tvSeparator2;
    private javax.swing.JSeparator tvSeparator3;
    private javax.swing.JSeparator tvSeparator4;
    private javax.swing.JLabel tvServicesLabel;
    private javax.swing.JCheckBox unreturnedRouterCheckbox;
    private javax.swing.JLabel visualArrowLabel;

    /**
     * Creates new form ParametersPage
     */
    public ParametersPage()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        tvServicesLabel = new javax.swing.JLabel();
        tvPackagesCombobox = new javax.swing.JComboBox<>();
        subTypeLabel = new javax.swing.JLabel();
        phoneServicesLabel = new javax.swing.JLabel();
        internetServicesLabel = new javax.swing.JLabel();
        tvInternetSeparator = new javax.swing.JSeparator();
        internetPhoneSeparator = new javax.swing.JSeparator();
        SubTypeComboBox = new javax.swing.JComboBox<>();
        tvPackagesLabel = new javax.swing.JLabel();
        stbCombobox = new javax.swing.JComboBox<>();
        boxesLabel = new javax.swing.JLabel();
        dvrLabel = new javax.swing.JLabel();
        stbLabel = new javax.swing.JLabel();
        dvrAddButton = new javax.swing.JButton();
        tvSeparator1 = new javax.swing.JSeparator();
        dvrEditButton = new javax.swing.JButton();
        stbEditButton = new javax.swing.JButton();
        dvtStbSerparator = new javax.swing.JSeparator();
        channelLabel = new javax.swing.JLabel();
        hdeliteCheckbox = new javax.swing.JCheckBox();
        starzCheckbox = new javax.swing.JCheckBox();
        sportstierCheckbox = new javax.swing.JCheckBox();
        showtimeCheckbox = new javax.swing.JCheckBox();
        cinemaxCheckbox = new javax.swing.JCheckBox();
        hboCheckbox = new javax.swing.JCheckBox();
        tvSeparator3 = new javax.swing.JSeparator();
        tvSeparator2 = new javax.swing.JSeparator();
        airtvLabel = new javax.swing.JLabel();
        airtvAntennaCheckbox = new javax.swing.JCheckBox();
        airtv2Checkbox = new javax.swing.JCheckBox();
        airtvAnywhereCheckbox = new javax.swing.JCheckBox();
        airtv2FlashdriveCheckbox = new javax.swing.JCheckBox();
        internetPackagesLabel = new javax.swing.JLabel();
        internetSpeedCombobox = new javax.swing.JComboBox<>();
        internetSeparator1 = new javax.swing.JSeparator();
        extrasLabel = new javax.swing.JLabel();
        routerCheckbox = new javax.swing.JCheckBox();
        visualArrowLabel = new javax.swing.JLabel();
        purchasedRouterCheckbox = new javax.swing.JCheckBox();
        unreturnedRouterCheckbox = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jComboBox5 = new javax.swing.JComboBox<>();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        phoneFiberLabel = new javax.swing.JLabel();
        newPhoneButton = new javax.swing.JButton();
        resetAllButton = new javax.swing.JButton();
        submitAllButton = new javax.swing.JButton();
        tvSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tvServicesLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tvServicesLabel.setText("TV Services");

        tvPackagesCombobox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tvPackagesCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "Basic IPTV", "Standard IPTV", "Preffered IPTV", "AirTV", "Streaming"}));
        tvPackagesCombobox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tvPackagesComboboxActionPerformed(evt);
            }
        });

        subTypeLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        subTypeLabel.setText("Subsciber Type:");

        phoneServicesLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        phoneServicesLabel.setText("Phone Services");

        internetServicesLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        internetServicesLabel.setText("Internet Services");

        tvInternetSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        internetPhoneSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SubTypeComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SubTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "Residential", "Student", "Business (Coming soon!)"}));

        tvPackagesLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tvPackagesLabel.setText("Packages");

        stbCombobox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stbCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "1", "2", "3", "4", "5", "6", "7", "8", "9"}));
        stbCombobox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stbComboboxActionPerformed(evt);
            }
        });

        boxesLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boxesLabel.setText("Boxes");

        dvrLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dvrLabel.setText("DVR");

        stbLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stbLabel.setText("STB");

        dvrAddButton.setText("Add");
        dvrAddButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dvrAddButtonActionPerformed(evt);
            }
        });

        dvrEditButton.setText("Edit");
        dvrEditButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dvrEditButtonActionPerformed(evt);
            }
        });

        stbEditButton.setText("Edit");
        stbEditButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stbEditButtonActionPerformed(evt);
            }
        });

        dvtStbSerparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        channelLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        channelLabel.setText("Channels");

        hdeliteCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hdeliteCheckbox.setText("HDElite");
        hdeliteCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hdeliteCheckboxActionPerformed(evt);
            }
        });

        starzCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        starzCheckbox.setText("Starz");
        starzCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                starzCheckboxActionPerformed(evt);
            }
        });

        sportstierCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sportstierCheckbox.setText("Sports Tier");
        sportstierCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sportstierCheckboxActionPerformed(evt);
            }
        });

        showtimeCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        showtimeCheckbox.setText("Showtime");

        cinemaxCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cinemaxCheckbox.setText("Cinemax");

        hboCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hboCheckbox.setText("HBO");

        airtvLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        airtvLabel.setText("Air Tv");

        airtvAntennaCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        airtvAntennaCheckbox.setText("AirTV Antenna");

        airtv2Checkbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        airtv2Checkbox.setText("AirTV2");

        airtvAnywhereCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        airtvAnywhereCheckbox.setText("AirTv Anywhere");

        airtv2FlashdriveCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        airtv2FlashdriveCheckbox.setText("AirTV2 Flashdrive");

        internetPackagesLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        internetPackagesLabel.setText("Packages");

        internetSpeedCombobox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        internetSpeedCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "2M", "100M", "200M", "500M", "1GB"}));
        internetSpeedCombobox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                internetSpeedComboboxActionPerformed(evt);
            }
        });

        extrasLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        extrasLabel.setText("Extras");

        routerCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        routerCheckbox.setText("Router");
        routerCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                routerCheckboxActionPerformed(evt);
            }
        });

        visualArrowLabel.setText("= = = = = = = = = = = =  >");

        purchasedRouterCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        purchasedRouterCheckbox.setText("Purchased Router");
        purchasedRouterCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                purchasedRouterCheckboxActionPerformed(evt);
            }
        });

        unreturnedRouterCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        unreturnedRouterCheckbox.setText("Unreturned Router");
        unreturnedRouterCheckbox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                unreturnedRouterCheckboxActionPerformed(evt);
            }
        });

        jCheckBox14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox14.setText("Static IP Address");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Ancillary");

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Tech Home Protect");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Tech Home Support");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("WholeHome Wifi Devices");

        jCheckBox15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox15.setText("Mobile Protect Addon");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox16.setText("Desktop Protect Addon");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox16ActionPerformed(evt);
            }
        });

        jCheckBox17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox17.setText("Mobile Protect Addon");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox17ActionPerformed(evt);
            }
        });

        jCheckBox18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox18.setText("Desktop Protect Addon");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox18ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "1", "2", "3", "4", "5", "6", "7", "8", "9"}));
        jComboBox5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Other");

        jCheckBox19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox19.setText("Speed Boost");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox19ActionPerformed(evt);
            }
        });

        phoneFiberLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phoneFiberLabel.setText("Fiber Phone 1000");

        newPhoneButton.setText("New Phone");
        newPhoneButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newPhoneButtonActionPerformed(evt);
            }
        });

        resetAllButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resetAllButton.setText("Reset");
        resetAllButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetAllButtonActionPerformed(evt);
            }
        });

        submitAllButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitAllButton.setText("Submit");
        submitAllButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submitAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tvSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(15, 15, 15)
                                                                                .addComponent(dvrLabel))
                                                                        .addComponent(dvrAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(dvrEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dvtStbSerparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(15, 15, 15)
                                                                                .addComponent(stbLabel))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(stbEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(stbCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(tvSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(tvServicesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(tvPackagesCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tvSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(63, 63, 63)
                                                                                .addComponent(channelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(71, 71, 71)
                                                                .addComponent(tvPackagesLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(88, 88, 88)
                                                                .addComponent(boxesLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(starzCheckbox)
                                                                        .addComponent(showtimeCheckbox)
                                                                        .addComponent(hdeliteCheckbox))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(sportstierCheckbox)
                                                                        .addComponent(cinemaxCheckbox)
                                                                        .addComponent(hboCheckbox)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(91, 91, 91)
                                                                .addComponent(airtvLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(airtv2FlashdriveCheckbox, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(airtvAntennaCheckbox, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(airtvAnywhereCheckbox, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(airtv2Checkbox, javax.swing.GroupLayout.Alignment.LEADING))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tvInternetSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(subTypeLabel)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(internetSeparator1)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                                                .addComponent(jCheckBox14)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                        .addComponent(routerCheckbox)
                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                        .addComponent(visualArrowLabel)
                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(unreturnedRouterCheckbox)
                                                                                                                                .addComponent(purchasedRouterCheckbox)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel15)
                                                                                                                                .addComponent(jCheckBox15)
                                                                                                                                .addComponent(jCheckBox16))
                                                                                                                        .addGap(18, 18, 18)
                                                                                                                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel16)
                                                                                                                                .addComponent(jCheckBox17)
                                                                                                                                .addComponent(jCheckBox18)))
                                                                                                                .addComponent(jSeparator11)
                                                                                                                .addComponent(jSeparator13)
                                                                                                                .addComponent(jSeparator14))
                                                                                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(50, 50, 50)
                                                                                                .addComponent(internetServicesLabel))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                .addGap(116, 116, 116)
                                                                                                                .addComponent(internetPackagesLabel))
                                                                                                        .addComponent(internetSpeedCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(139, 139, 139)
                                                                                                .addComponent(extrasLabel))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(136, 136, 136)
                                                                                                .addComponent(jLabel14))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(49, 49, 49)
                                                                                                .addComponent(jLabel17))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(152, 152, 152)
                                                                                                .addComponent(jLabel18)))
                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(121, 121, 121)
                                                                .addComponent(jCheckBox19)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addComponent(internetPhoneSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(resetAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(submitAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addComponent(phoneFiberLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(newPhoneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(46, 46, 46))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(phoneServicesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(tvSeparator4))
                                                                .addGap(19, 19, 19))))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(SubTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(subTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phoneServicesLabel)
                                                        .addComponent(internetServicesLabel)
                                                        .addComponent(tvServicesLabel))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(tvPackagesLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(tvPackagesCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(tvSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(boxesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(dvtStbSerparator, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(stbLabel)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(stbCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(stbEditButton))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(dvrLabel)
                                                                                                .addGap(9, 9, 9)
                                                                                                .addComponent(dvrAddButton)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(dvrEditButton)))
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(tvSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(channelLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(hdeliteCheckbox)
                                                                                        .addComponent(sportstierCheckbox))
                                                                                .addGap(3, 3, 3)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(cinemaxCheckbox)
                                                                                        .addComponent(starzCheckbox))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(showtimeCheckbox)
                                                                                        .addComponent(hboCheckbox))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(tvSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(airtvLabel)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(airtvAntennaCheckbox)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(airtv2FlashdriveCheckbox)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(airtvAnywhereCheckbox)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(airtv2Checkbox))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(internetPackagesLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(internetSpeedCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(internetSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(extrasLabel)
                                                                                .addGap(16, 16, 16)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(routerCheckbox)
                                                                                        .addComponent(visualArrowLabel)
                                                                                        .addComponent(purchasedRouterCheckbox))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(unreturnedRouterCheckbox)
                                                                                .addGap(9, 9, 9)
                                                                                .addComponent(jCheckBox14)
                                                                                .addGap(31, 31, 31)
                                                                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel14)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(8, 8, 8)
                                                                                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel16)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jCheckBox17)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jCheckBox18))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel15)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jCheckBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jCheckBox16)))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel17)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel18)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jCheckBox19)
                                                                .addGap(0, 31, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(phoneFiberLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(newPhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(tvSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(resetAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(submitAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(40, 40, 40))))
                                        .addComponent(tvInternetSeparator)
                                        .addComponent(internetPhoneSeparator))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void tvPackagesComboboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void stbComboboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void dvrEditButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new DVRPage().setVisible(true);
            }
        });
    }

    private void hdeliteCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void sportstierCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void starzCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void internetSpeedComboboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void routerCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void purchasedRouterCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void unreturnedRouterCheckboxActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void newPhoneButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void resetAllButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }

    private void submitAllButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        dispose();

        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new BatchOptionsPage().setVisible(true);
            }
        });
    }

    private void stbEditButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new STBPage().setVisible(true);
            }
        });
    }

    private void dvrAddButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
    }
    // End of variables declaration
}
